sudo: required
services:
  - docker

before_install:
  - docker build -t harbsidhu/aws-react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true harbsidhu/aws-react-test npm run test

after_success:
  - docker build -t harbsidhu/aws-multi-client ./client
  - docker build -t harbsidhu/aws-multi-nginx ./nginx
  - docker build -t harbsidhu/aws-multi-server ./server
  - docker build -t harbsidhu/aws-multi-worker ./worker
  
# Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# Take those images and push them to docker hub
  - docker push harbsidhu/aws-multi-client
  - docker push harbsidhu/aws-multi-nginx
  - docker push harbsidhu/aws-multi-server
  - docker push harbsidhu/aws-multi-worker

#deploy:
#  provider: elasticbeanstalk
#  region: us-west-1
#  app: multi-docker
#  env: MultiDocker-env
#  bucket_name: elasticbeanstalk-us-west-1-306476627547
#  bucket_path: docker-multi
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key:
#    secure: $AWS_SECRET_KEY
